# Spring Boot Application Configuration
spring.application.name=time-deposit-api

# Logging
logging.level.root=INFO
logging.level.org.ikigaidigital=DEBUG

# Springdoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
