spring:
  application:
    name: time-deposit-api
  datasource:
    url: jdbc:postgresql://localhost:5432/time_deposit
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: false

logging:
  level:
    root: INFO
    org.ikigaidigital: DEBUG
    org.flywaydb: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

time-deposit:
  grace-period-days: 30
  months-in-year: 12
  plans:
    basic:
      interest-rate: 0.01
    student:
      interest-rate: 0.03
      max-interest-days: 365
    premium:
      interest-rate: 0.05
      interest-start-days: 45
